travis:
  secure:
    BINSTAR_TOKEN: kgBg6wsqP+BMkXtGid6hoEfndyAlc0eSz+NjfeIQJbTVNxWrAWrFA5Cu3C9VzafFCaltnkoWnBRo3b/UsHovBFkCqWfg6+hxKLPhJBuVwV88aQNj+Sctut6LC7UlrDNrJ/j4fN2rLbZ+j8anDP9ETQhUBAOknXbfYF90xqeD8xedQpztbWzRDDiJH7eYBTPAz+HhrOD2GJCLHphKjSGVLwDipCj1mDBAm4slvIRH+nf/P0v6LClOKqbev6eT+XvUbCrKfSOgvxay6N2ZmvbfkGGcgqFOPTmI2rWwfjf/r8LixbTFPaY3yv9Pv9Ssn4JVbT+fL3ADbOY914pb4QHhP/Grfp2PC+7V5KGlWcotinhvJ8njr6uVjdSpgDQy4MP6MjLm1KpdgL96nOclSEb2B6EKqFODmQG8Hgkal2ilXCzyoeHXM4kxfBg9GxHj/vfC1ejyQfHrkXcvUYwoytz1LVizlFgA9Sjs5hS2j0ARQO2sBfdFsoxkF/2jH9f2FbYNg9NEVOUl4SpRra5AhCmHckYwAnDevH+SXVRdoqPkiGfCxfeEKKVrrBHAQHoHiK4VUMePnJuJuG+S6wEwsDe7fIjd+r+JdQRTNvNPQU0ZHbyABy12K3ZT2JSXYs8TBlnm8sISzOmSiU1l5XOm5dItKoxQBJHxM44E1SWugk9cIs4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
